@host=https://localhost:7060

GET {{host}}/dinners HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzA0YzcyZS1jNTJmLTRlY2EtODZiNy0zNzhlZjM0NjRkOWUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiOTA5YTdmOWYtMjBhYS00YTY1LWEyOTQtNWRlNWFjN2ZkMTBiIiwiZXhwIjoxNjc0MTQyMjM2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.HfyDgGeTKB97vCQHnjEf9jsEd-2lut1t7Y5YEES8glQ